// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeO6zs-gUWYitMnImoU_IKTneScfKSWyw',
    appId: '1:510012734265:android:f94788566c33e71db546e8',
    messagingSenderId: '510012734265',
    projectId: 'delicebko',
    databaseURL: 'https://delicebko-default-rtdb.firebaseio.com',
    storageBucket: 'delicebko.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZERwn9kGETX0UkAE5Okd7gzH_4v1UzmU',
    appId: '1:510012734265:ios:74205aa0d356e348b546e8',
    messagingSenderId: '510012734265',
    projectId: 'delicebko',
    databaseURL: 'https://delicebko-default-rtdb.firebaseio.com',
    storageBucket: 'delicebko.appspot.com',
    iosClientId: '510012734265-85jfcrtssmsa8ogl4qv2torp3ts9ssph.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliceBko',
  );
}
